# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
