# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 04:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stweb', '0002_auto_20171106_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
            preserve_default=False,
        ),
    ]
